version: '3.8'

services:
  94list-laravel:
    container_name: 94list-laravel
    # 镜像名字
    image: huankong233/94list-laravel:latest
    # 网络模式
    # "bridge"为网桥模式,"host"为主机模式
    network_mode: 'bridge'
    #开放端口
    ports:
      # 左边为外部开放端口，右边为容器内端口，请勿修改右边端口
      - '8080:8080'
    # 目录映射
    volumes:
      # 左侧为宿主机目录，请自行修改，右侧为容器内部目录，请勿修改
      - ./path/94list-laravel/html:/var/www/html
    # 重启策略
    restart: always
    # 环境变量
    environment:
      ### 模式选择
      #  0 为.env模式
      #  1 为容器环境变量模式 
      # 使用模式0时，必须#注释或删除掉"数据库配置"大项，否则会出现参数被环境变量代替的情况
      # 使用模式1时，可搭配下方数据库配置一同使用
      - APP_INSTALL_MODE=1

      ### 基础配置
      # 网站名字
      #- APP_NAME=94list-laravel
      # 网站地址
      #- APP_URL=http://localhost

      ### 数据库配置
      # db_type有效参数，"sqlite"、"mysql"
      # 如果需要使用sqlite请手动创建好一个空文件，然后在DB_DATABASE中指定数据库文件的绝对位置
      #- DB_CONNECTION=mysql
      # 数据库地址
      #- DB_HOST=127.0.0.1
      # 数据库端口
      #- DB_PORT=3306
      # 数据库名字
      #- DB_DATABASE=94list
      # 用户名
      #- DB_USERNAME=94list
      # 登陆密码
      #- DB_PASSWORD=passwd

      ### 邮箱配置
      # 邮件服务器协议类型
      #- MAIL_MAILER=smtp
      # 邮件服务器地址
      #- MAIL_HOST=smtp.qq.com
      # 邮件服务器端口
      #- MAIL_PORT=465
      # 邮件服务器登陆账号
      #- MAIL_USERNAME=hello@example.com
      # 邮件服务器授权码（注意！非账号登陆密码）
      #- MAIL_PASSWORD=passwd
      # 邮件服务器加密类型
      #- MAIL_ENCRYPTION=TLS
      # 发送人名字
      #- MAIL_FROM_ADDRESS=hello@example.com
      # 自定义用户名
      #- MAIL_FROM_NAME=自定义用户名
